NumPy : 
    Numeric Python
    Alternative to Python lists : Numpy Array
    Calculation over entire Arrays
    Easy  & Fast
    Installation

In the terminal Pip3 Install Numpy

In [1]:
import numpy as np

#### initializing a numpy array

###### intializing a 1D numpy array

In [3]:
onedim_ary = np.array([1,2,3], ndmin=2) 

In [4]:
onedim_ary

array([[1, 2, 3]])

In [247]:
# initializing with list
    onedim_ary = np.array([1,2,3]) 
# print(onedim_ary)

# number of dimension (D) of an array. Is it 1D, 2D, 3D and nD?
    print("Dimension of array:::", onedim_ary.ndim)
# shape of an array, output:tuple(dimension, rows, columns)
    print("Shape of array (dimension, rows, columns):::", onedim_ary.shape)
# number of elements in an array
    print("number of elements in array:::", onedim_ary.size) 
# datatype of the array
    print("datatype of the array:::", type(onedim_ary)) 
# datatype of the values inside an array
    print("datatype of values inside array:::", onedim_ary.dtype) 
    print("datatype of values inside array:::", onedim_ary.dtype.name) 

Dimension of array::: 1
Shape of array (dimension, rows, columns)::: (3,)
number of elements in array::: 3
datatype of the array::: <class 'numpy.ndarray'>
datatype of values inside array::: int32
datatype of values inside array::: int32


##### multiple ways to initialize a numpy array

In [ ]:
# initialize a 2D numpy array
    twodim_array = np.array([[2,3,4],[5,6,7]])
    print("Shape of array (dimension, rows, columns):::", init_list_array.shape)

# initialize a numpy array with value zero
    zero_val_array = np.zeros((2,2,3))
    print("zero value array::: \n", zero_val_array)
    print("shape of zero value array:::", zero_val_array.shape)

# initialize a numpy array with value one
    one_val_array = np.ones((2,3,3), dtype=np.int32)
    print("one value array::: \n", one_val_array)
    print("shape of one value array:::", one_val_array.shape)

# initialize a numpy array with required value
    rqd_val_array = np.full((2,3,3), 10)
    print("rqd value array::: \n", rqd_val_array)
    print("shape of rqd value array:::", rqd_val_array.shape)

# initialize a numpy array with value one
# rnd1_val_array = np.empty((2,3,3))
# print("rnd value array::: \n", rnd_val_array)
# print("shape of rnd value array:::", rnd_val_array.shape)

# initialize a numpy array with odd number
# can generate any sequence of nbrs like "even numbers" or "steps of 5" like 5, 10, 15...
    odd_nbr_ary = np.arange(1,100,2).reshape(2,25)
    print("odd number ary::: \n", odd_nbr_ary)
    print("shape of odd number array:::", odd_nbr_ary.shape)

# initialize a numpy array with floating point value for percentiles
    percentiles_ary = np.linspace(0.1,1,10)
    print("percentiles ary::: \n", percentiles_ary)
    print("shape of percentiles ary:::", percentiles_ary.shape)

#### distinct values from an array

In [ ]:
ary = np.array([[1,2,3,4,5],[3,4,5,6,7]])
print(ary)
st = np.unique(ary)
print(ary, st)

#### Flatten

In [ ]:
mul_dim_array.flatten()
print(mul_dim_array)
np.m

#### Delete

In [ ]:
mul_dim_array = np.array(np.arange(1,21)).reshape(4,5)
print(mul_dim_array)
mul_dim_array1 = mul_dim_array.copy()
# second argument in the delete function it position of the row or column, 3rd argument is axis (row delete or column delete)
np.delete(mul_dim_array1, 3, 0)

#### Insert

##### modify at multiple index using list

In [ ]:
mul_dim_array = np.array(np.arange(1,21)).reshape(4,5)
print(mul_dim_array)
np.put(mul_dim_array, [0,1,5,15], -5)
print(mul_dim_array)
mul_dim_array[0][0] = 10
print(mul_dim_array)

##### modify at multiple index using array

In [ ]:
mul_dim_array = np.array(np.arange(1,11)).reshape(2,5)
print(mul_dim_array)
x = np.array([1,2,0,1]).reshape(2,2)
np.put_along_axis(mul_dim_array, x, 99, axis=1)
print(mul_dim_array)

##### modify based on condition

In [ ]:
arr = np.arange(6).reshape(2, 3)
print(arr)
np.place(arr, arr>2, 55)
arr

#### Arithmetic operations

In [6]:
num_array = np.array(np.arange(2,12))
num_array1 = np.array(np.arange(2,12))

In [7]:
num_array + num_array1

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [ ]:
num_array = np.array(np.arange(2,12))
print("\n Base array\t:::", num_array)
print("\n Exponentiation\t ** 2\t:::", num_array ** 2)
print("\n Division\t /2 \t:::", num_array / 2)
print("\n Multiplication\t *2 \t:::", num_array * 2)
print("\n Addition\t +2 \t:::", num_array + 2)
print("\n Subtraction\t -2 \t:::", num_array - 2)

####  Logical operations

In [ ]:
num_array = np.array(np.arange(1,21).reshape(2,2,5))
multiply_index = num_array > 6
print(multiply_index)
num_array[multiply_index] *= 0
print(num_array)

#### Transpose 

In [ ]:
print("\n Original array:::", twodim_array)
twodim_array_tp = np.transpose(twodim_array)
print("\n Original array:::", twodim_array_tp)

#### Appending - Concatenating axis must be same

##### Append function

In [ ]:
ary1 = np.arange(1,21).reshape(2,2,5)
ary2 = np.arange(21,41).reshape(2,2,5)
print(ary1, "\n", ary2)
np.append(ary1, ary2, axis=2)

In [1]:
ary2 = np.arange(21,41).reshape(2,2,5)

NameError: name 'np' is not defined

##### vstack - dimension (1D, 2D, 3D) and column must be same, rows not necessary

In [ ]:
mul_5 = np.arange(5,55,5).reshape(2,5)
mul_2 = np.arange(2,41,2).reshape(4,5)
vstac = np.vstack((mul_5, mul_2))
print("\n vertical stacked arrays \n:::", vstac)

##### hstack - dimension (1D, 2D, 3D) and rows must be same, columns not necessary

In [ ]:
mul_5 = np.arange(5,55,5).reshape(2,5)
mul_2 = np.arange(2,21,2).reshape(2,5)
hstac = np.hstack((mul_5, mul_2))
print("\n vertical stacked arrays \n:::", hstac)

#### Split

##### vsplit - 
    to split into N number of arrays, the array axes should have N * y elements (N * y rows)
    first argument is number of columns, second argument is number of array

In [ ]:
mul_5 = np.arange(5,55,5).reshape(5,2)
a, b, c = np.vsplit(mul_5, [2,4])
print(a, "\n\n", b, "\n\n", c)

##### hsplit - 
    to split into N number of arrays, the array axes should have N * y elements (N * y cols)
    first argument is number of columns, second argument is number of array

In [ ]:
mul_5 = np.arange(5,55,5).reshape(2,5)
a, b, c = np.hsplit(mul_5, [2,4])
print(a, "\n\n", b, "\n\n", c)

#### stat functions

##### amin, amax, argmin, argmax

In [ ]:
    a = np.arange(5,155,5).reshape(2,3,5)
    a = np.vstack((a, np.arange(1,16).reshape(1,3,5)))
    print(a)
    print("shape of array:::", a.shape)
# axis = 0 gives the dimension that is a minimum of sum of all the values in a given dimension
    print("min val of entire array:::", np.amin(a, axis = 0))
    print("min val of column:::", np.amin(a, axis = 1))
    print("min val of row:::", np.amin(a, axis = 2))
# amax, nanmin, nanmax

In [ ]:
a = np.arange(5,155,5).reshape(3,10)
a[1][5] = 750
print(a)
min_ind = np.argmin(a, axis = 0)
print(min_ind)
max_ind = np.argmax(a, axis = 0)
print(max_ind)
a[max_ind][:]

##### ptp (Range: max - min)

In [ ]:
# range of values (maximum - minimum)
    print("Range of entire array:::", np.ptp(a, axis = 0))
    print("Range of column:::", np.ptp(a, axis = 1))
    print("Range of row:::", np.ptp(a, axis = 2))  

##### percentile

In [86]:
?np.percentile

In [ ]:
# percentiles of the given array
ary_stat = np.vstack((np.arange(1,16). reshape(1,3,5), 
                         np.arange(251,266). reshape(1,3,5), 
                         np.arange(751,766). reshape(1,3,5),
                         np.arange(991,1006). reshape(1,3,5)))
print(ary_stat)
print("\npercentile value of entire array:::\n", np.percentile(ary_stat, 25, axis=0))
print("\npercentile value of columns:::\n", np.percentile(ary_stat, 60, axis=1))

In [115]:
ary_stat = np.arange(100,150). reshape(2,25)
print(ary_stat)
print(ary_stat.shape)
print( np.percentile(ary_stat, 40, axis=1, interpolation = 'linear', keepdims=True))
print( np.percentile(ary_stat, 40, axis=1, interpolation = 'lower', keepdims=True))
print( np.percentile(ary_stat, 40, axis=1, interpolation = 'higher', keepdims=True))
print( np.percentile(ary_stat, 40, axis=1, interpolation = 'nearest', keepdims=True))
print( np.percentile(ary_stat, 40, axis=1, interpolation = 'midpoint', keepdims=True))

[[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119 120 121 122 123 124]
 [125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142
  143 144 145 146 147 148 149]]
(2, 25)
[[109.6]
 [134.6]]
[[109]
 [134]]
[[110]
 [135]]
[[110]
 [135]]
[[109.5]
 [134.5]]


#####  Measures of CENTRAL TENDENCY

##### Mean

In [ ]:
# Mean of the given array
print(ary_stat)
print("\n Mean of entire array:::\n", np.mean(ary_stat, axis=0))
print("\n Mean of each column:::\n", np.mean(ary_stat, axis=1))
print("\n Mean of each row:::\n", np.mean(ary_stat, axis=2))
# weighted average
print("\n Mean of each row:::\n", np.average(ary_stat, axis=2, weights=[5, 3, 4, 2, 1]))

##### Median

In [ ]:
print(ary_stat)
print("\n Median of entire array:::\n", np.median(ary_stat, axis=0))
print("\n Median of each column:::\n", np.median(ary_stat, axis=1))
print("\n Median of each row:::\n", np.median(ary_stat, axis=2))

#### Dispersion

##### Standard Deviation

In [ ]:
print(ary_stat)
print("\n Std Dev of entire array:::\n", np.std(ary_stat, axis=0))
print("\n Std Dev of each column:::\n", np.std(ary_stat, axis=1))
print("\n Std Dev of each row:::\n", np.std(ary_stat, axis=2))

##### Variance

In [ ]:
print(ary_stat)
print("\n Variance of entire array:::\n", np.var(ary_stat, axis=0))
print("\n Variance of each column:::\n", np.var(ary_stat, axis=1))
print("\n Variance of each row:::\n", np.var(ary_stat, axis=2))

#### Sampling
    sample is typically a small subset of the population
    

##### random sampling

In [ ]:
s = np.random.random_sample(100).reshape(2,50)

##### Sampling from a normal distribution

In [ ]:
s = np.random.normal(5, 3, 100).reshape(2,50)
print(np.mean(s))
print(np.median(s))
print(np.std(s))

In [12]:
named_ary = np.array([(1,2), (4,6)], dtype=[('x', int),('y', int)])
print(named_ary, named_ary.shape)
named_ary = named_ary.view(np.recarray)
print(named_ary)
named_ary['x']

[(1, 2) (4, 6)] (2,)
[(1, 2) (4, 6)]


array([1, 4])

In [18]:
s = np.random.normal(5, 3, 20).reshape(2,2,5)
s

array([[[ 7.89494223,  1.85463258,  3.97178456,  9.68729572,
          7.25651779],
        [ 4.92441463,  5.82685383,  1.95303239, -0.44520954,
         -1.31722907]],

       [[ 7.52216727,  8.20453942,  2.73708407,  7.05954232,
          6.06645601],
        [ 2.60587362, -1.20009077,  3.40906796,  4.333375  ,
          1.76038395]]])

array([[ 7.89494223,  1.85463258,  3.97178456,  9.68729572,  7.25651779],
       [ 4.92441463,  5.82685383,  1.95303239, -0.44520954, -1.31722907]])